//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Addin.Interface
{
	using Common.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IAddinWorkQueue<TWorkItem, TWorkResult> 
		where TWorkItem : IWorkItem
		where TWorkResult : IWorkResult
	{
		IEnumerable<IContextualWorkResult<TWorkItem, TWorkResult>> Results { get; }

		bool IsComplete { get; }

		bool IsEnqueuingCompleted { get; }

		void Enqueue(IWorkItem workItem);

		void Enqueue(IEnumerable<IWorkItem> workItems);

		void Start();

		void CompleteEnqueuing();

		void Initialize(IWorkCommand workCommand);

	}
}

