//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Addin.Interface
{
	using Addin;
	using Common.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IAddin 
	{
		string Name { get;set; }

		string Author { get;set; }

		IEnumerable<IMenuExtension> MenuExtensions { get; }

		IMenuExtension Launch { get;set; }

		AddinType AddinType { get;set; }

		void Initialize(IServiceLocator serviceLocator);

	}
}

