//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Addin.Interface
{
	using Common.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IContextualWorkResult<TWorkItem, TWorkResult> 
		where TWorkItem : IWorkItem
		where TWorkResult : IWorkResult
	{
		TWorkResult WorkResult { get;set; }

		TWorkItem WorkItem { get;set; }

	}
}

