//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Addin.Interface
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IMenuExtension 
	{
		string Name { get;set; }

		System.Windows.Input.ICommand Command { get;set; }

	}
}

