//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum LogLevel : int
	{
		Fatal = 1,
		Warning = 3,
		Error = 2,
		Info = 4,
		Debug = 5,
	}
}
