//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class WorkerInfo
	{
		public virtual string Id
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

	}
}

