//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using Common.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class WorkContext
	{
		public virtual IEnumerable<System.Byte> WorkCommandFile
		{
			get;
			set;
		}

	}
}

