//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using Common.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class WorkQueueInfo
	{
		public virtual System.Uri WorkQueueContextLocation
		{
			get;
			set;
		}

		public virtual System.Uri WorkQueueLocation
		{
			get;
			set;
		}

	}
}

