//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IFileService 
	{
		System.IO.FileStream OpenFile(string path);

		void DeleteFile(string path);

		void CreateDirectory(string dir);

		void DeleteDirectory(string dir);

	}
}

