//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Interfaces
{
	using Common;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ILoggingService 
	{
		void Log(LogLevel level, string description);

		void Log(LogLevel level, string description, System.Exception exception);

	}
}

