//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IWorkResult 
	{
		bool Success { get;set; }

		System.Exception Error { get;set; }

		System.Guid WorkItemId { get;set; }

	}
}

